server.port=8080
spring.application.name=book-ai-backend

spring.config.import=optional:file:.env[.properties]

# Lee la variable de entorno, y si no existe por algún motivo, usa la URL de fallback
n8n.webhook.url=${N8N_WEBHOOK_URL:http://localhost:5678}

openlibrary.api.url=https://openlibrary.org
logging.level.com.bookai.client=DEBUG

# Configuracion de OpenFeign para aumentar el tiempo de espera a 60 segundos
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=60000